### ISSUE TITLE
Option to hide Komet from the doc

### ISSUE THREAD

**Issue by thenikso** [zorgiepoo/Komet#6]
I've did this to have Komet not appear in the doc when I `git commit` from the command line. I like it better this way:

``` shell
defaults write /Applications/Komet.app/Contents/Info.plist LSUIElement true
```

Maybe an option in the settings to achieve the same effect could be added.

PS: great job, I'll be using Komet as my default commit message editor 🚀

**Comment by zorgiepoo** [comment]
I did initially want to use Komet without having a dock icon but later changed my mind since it becomes harder to switch back to Komet from another app. Hope this wouldn't be the same case for you!

If an option is still wanted despite that, then an option should be added. It would have to work a different way though than writing to info.plist. Just hope the icon can be hidden before it shows up.

**Comment by thenikso** [comment]
Indeed I had the same issue of not being able to alt-tab to Komet. for now I'm just "exposéing" my way to it if needed and it's all right. a solution could be to have another option to always keep Komet in the front?

**Comment by zorgiepoo** [comment]
Yeah, like a global hotkey or have it show up in the menu bar. But I think this may be overkill. On second thought, I don't think there is much benefit to hiding the app from the dock. As you can see, it makes things difficult, and Komet is not an app that stays running forever in the background.

**Comment by zorgiepoo** [comment]
I don't think this should be a supported option.
